version: '2'
services:
  mysqldb:
    image: localhost:5000/mysql
    volumes:
      - "/data/mysql:/var/data/mysql"
    restart: always
    expose:
      - "3306"

  demoapp:
    depends_on:
      - mysqldb
    build: .
    image: localhost:5000/demo
    restart: always
    environment:
      DB_CONNECTION_URL: mysqldb:3306
      DB_SCHEMA: demo
      DB_USER: demouser
      DB_PASSWORD: demopassword
    labels:
       - "traefik.backend=demoapp"
       - "traefik.frontend.rule=Host:demoapp.docker.localhost"
networks:
  default:
    external:
      name: traefik_webgateway
